### ISSUE TITLE
Version 0.7 meta-ticket

### ISSUE THREAD

**Issue by michielbdejong** [ledgerloops/ledgerloops#8]
- [ ] ddcd-dfs one-track probing
- [ ] ddcd-dfs multi-track probing
- [ ] ddcd-dfs message routing
- [ ] unicurn definition and convertor
- [ ] multi-currency peer-ledger
- [ ] ledgerloops-peer receives cycleFound event from ddcd-dfs, then:
  * reserves funds on peer-ledger,
  * creates ledgerloops-challenge,
  * sends conditional-promise
- [ ] ledgerloops-peer deals with conditional-promise, satisfy-condition, [please-]reject

**Comment by michielbdejong** [comment]
Since I've been out of it in two years, and I'm no longer so sure about how ddcd-dfs is decoupled from the ledger updates in this design, I'm thinking of making 0.7 a rewrite from scratch. The plan would then be:

* [ ] get WebSocket hub working (again)
* [ ] implement peer ledger (exposes functions for the various message types, keeps a copy of the ledger)
* [ ] implement ddcd-dfs on top of it
* [ ] nice demo UI
